### ISSUE TITLE
feat(cli-adapters): normalized capacity_exhausted diagnostic + capacity-aware routing exclusion (#4351 criterion 3) — exclusion held on #4456

### ISSUE THREAD

**Issue by williamzujkowski** [nexus-substrate/nexus-agents#4373]
Child of #4351 (criterion 3). Split out after auditing the acceptance criteria against `e4d1cc929f` — the terminal-state increments (#4362, #4363) do not touch this.

## What is missing

**No normalized capacity diagnostic exists.** `grep -rn "capacity_exhausted"` returns nothing tree-wide. `CliErrorCode` (`cli-adapters/types-core.ts:108-118`) carries `RATE_LIMITED` / `BUDGET_EXCEEDED` / `UNKNOWN`, none of which distinguishes "this key is out of weekly quota" from "slow down, you are being throttled". `RATE_LIMIT_PATTERNS` (`orchestration/outcomes/outcome-types.ts:146-154`) has no weekly-quota or context-window pattern, so the outcome taxonomy cannot classify it either.

**Capacity is tracked but never routed on.** `CompositeRouter.getCapacityDashboard()` (`cli-adapters/composite-router.ts:1028`) is read-only. Nothing in `composite-router.ts` or `composite-router-helpers.ts` consults `CapacityStatus.exhausted` or `getCapacity()` to exclude an arm or trigger failover. The capacity tracker exists, has tests, and has no routing consumer.

## What already landed, so scope this correctly

#4330 (PR #4370) fixed the **CLI voter-panel** half by a different mechanism: `BaseCliAdapter` now feeds `defaultCliCircuitBreakerRegistry`, so a rate-limited CLI trips its breaker and `isCliServingForVoters` drops it from the next panel. That is failover-by-circuit-breaker, driven by observed failures.

This issue is the complementary path: excluding an arm *before* it fails, from capacity the tracker already holds, and giving the failure a diagnostic specific enough for a caller to act on. Do not duplicate the breaker mechanism — the two should compose, not race.

## Acceptance

- A normalized capacity-exhaustion code/category, distinct from generic rate-limiting, produced by the adapters that can detect it
- `CompositeRouter` excludes an exhausted arm, with a test proving exclusion (not just that the dashboard reports it)
- No-quorum behaviour when too few healthy voters remain after exclusion
- An adapter-level test for the authenticated-but-weekly-exhausted case — the state that produced the #4351 report, where every voter returned `stop_sequence` with zero tokens and the panel still reported healthy capacity

## Related

Blocked by nothing. Interacts with #4368 (whether breaker state needs to survive a process boundary) — a capacity signal that is durable across runs would partly subsume that question.

**Comment by williamzujkowski** [comment]
**Sequencing note (backlog grooming, 2026-08-14): the capacity-exclusion logic this issue asks for may already exist, unwired.**

`context/work-balancer.ts` already implements exactly the scoring-and-exclusion behaviour described here:

- `getCapacityScore` (line 267) — line 378: `if (capacity.exhausted || capacity.remainingTokens <= 0) return 0;` — an exhausted adapter scores zero
- `getNextQueuedTask` (line 312) — line 315 gates dispatch on `task.profile.estimatedTokens <= capacity.remainingTokens`

Per #4378, `WorkBalancer` has **zero production consumers** — it is re-exported from `context/index.ts` and never instantiated outside tests.

So the real decision is *wire vs. rebuild*, and it should be made before writing new exclusion logic in `CompositeRouter`. Building a second implementation here would create exactly the parallel-implementation duplication the canonical-paths rule forbids.

**Recommend sequencing #4378 before this issue.** Note #4378's disposition is not obviously 'delete' — per the research-intent rule, under-wired code is often interrupted work rather than dead code, and this is a case where the unwired component is a direct answer to a live need.

**Comment by williamzujkowski** [comment]
**Correction to my earlier comment (2026-08-14): the wire-vs-rebuild question is now settled, and the answer is REBUILD.**

I suggested above that `WorkBalancer` may already contain what this issue needs and that wiring it might beat building fresh. A live 7-voter `higher_order` panel voted **7/0 to delete it** — full reasoning and verification recorded on #4378.

Why my framing was wrong: `WorkBalancer` (`context/work-balancer.ts:250-264`) carries its own weighted capability scoring, duplicating what `SharedTaskAnalyzer` + `TopsisRouter` own canonically. It is a parallel routing implementation, not a queue with useful capacity helpers — so injecting it into the routing chain would *commit* the anti-sprawl violation I invoked it to avoid. Of its 388 lines, roughly 6 are the capacity semantics this issue needs.

**What this means for #4373, as binding conditions from the vote:**

1. Implement capacity exclusion as a **predicate inside the existing `CompositeRouter` stage chain** — not a new module, and not by consuming `WorkBalancer`.
2. **Port `work-balancer.test.ts`'s capacity-semantics assertions as this issue's red tests** before writing the implementation (exhausted flag, zero-remaining, estimate-vs-remaining boundary). The semantics survive as executable tests even though the code does not.
3. #4378's deletion PR lands **first** and separately; green CI on it is the proof that nothing consumed the old path.

Sequencing recommendation from my earlier comment stands — #4378 before this — only the disposition changed.

**Comment by williamzujkowski** [comment]
## Preserved capacity semantics — seed tests for this issue (binding condition 2 of the #4378 vote)

`work-balancer.test.ts` (42 passing tests, verified green 2026-08-15 before deletion) is being removed with #4378. Per the vote's binding condition 2, its **capacity-semantics assertions must be ported as this issue's red tests** so the knowledge survives as executable spec even though the implementation is rewritten. Transcribed here so the port does not depend on git archaeology.

### 1. Exclusion — an exhausted adapter is excluded, and the failure is a *normalized code*

```ts
it('should exclude adapters with exhausted capacity', () => {
  const exhaustedCapacity = createCapacityInfo({ exhausted: true, remainingTokens: 0 });
  const capacities = new Map([['claude', exhaustedCapacity]]);
  const result = balancer.balance(task, [adapter], capacities);
  expect(result.ok).toBe(false);
  expect(result.error.balancingCode).toBe('ALL_EXHAUSTED');
});
```

**This is the most load-bearing find for this issue.** A normalized exhaustion diagnostic already exists in-tree as `balancingCode: 'ALL_EXHAUSTED'`, with a distinct sibling case (all adapters exhausted vs. this one) that also asserts `ALL_EXHAUSTED` at line 183. This issue asks for a normalized `capacity_exhausted` diagnostic — **reuse or deliberately supersede the existing `ALL_EXHAUSTED` vocabulary rather than inventing a third spelling.** Introducing `capacity_exhausted` alongside a surviving `ALL_EXHAUSTED` would recreate, in diagnostics, exactly the duplication #4378 deleted in code.

### 2. Boundary behaviour — `getCapacityScore(capacity, task)`

| Condition | Expected | Test |
|---|---|---|
| `exhausted: true` | `0` | `should return 0 for exhausted capacity` |
| `remaining >= 2x estimated` (25k vs 10k) | `10` | `should return 10 for 2x or more capacity` |
| `remaining == estimated` (10k vs 10k) | `5` | `should return 5 for exactly matching capacity` |
| `1.5x` (15k vs 10k) | `≈7.5` | `should scale linearly between 1x and 2x` |
| `0.5x` (5k vs 10k) | `≈2.5` | `should decay for less than 1x capacity` |

Source formula (`work-balancer.ts:267-273`):

```ts
if (capacity.exhausted) return 0;
const tokenRatio = capacity.remainingTokens / task.estimatedTokens;
if (tokenRatio >= 2) return 10;
if (tokenRatio >= 1) return 5 + (tokenRatio - 1) * 5;
return Math.max(0, tokenRatio * 5);
```

Note the second, stricter variant at `work-balancer.ts:378` — `if (capacity.exhausted || capacity.remainingTokens <= 0) return 0;` — which also guards `remainingTokens <= 0` independently of the `exhausted` flag. **Port the stricter form**: a provider reporting `remainingTokens: 0` without setting `exhausted` must still be excluded, and there is a `estimatedTokens: 0` fixture (test line 121) implying a divide-by-zero path worth an explicit assertion.

### 3. Dispatch gate

`getNextQueuedTask` (`work-balancer.ts:315`) gated on `task.profile.estimatedTokens <= capacity.remainingTokens`. The queueing half is deliberately **not** ported — it is the shape mismatch that decided the #4378 vote. Only the comparison semantics carry over.

### Scope reminder

Per binding condition 1, the implementation is a predicate **inside the existing `CompositeRouter` stage chain** (`Budget → Zero → Preference → Topsis → LinUCB`), not a new module and not a revived component.

**Comment by williamzujkowski** [comment]
Refinement to the seed note above: I checked whether the `balancingCode`/`ALL_EXHAUSTED` vocabulary escapes `WorkBalancer`. It does not — `grep -rn "ALL_EXHAUSTED\|balancingCode" packages/nexus-agents/src/` returns **zero hits outside `work-balancer*`**.

So the vocabulary dies with #4378's deletion, and this issue is free to use `capacity_exhausted` as its normalized code without creating a competing spelling. The 'reuse or supersede' caution above only applies if some other diagnostic vocabulary surfaces during implementation.

**Comment by williamzujkowski** [comment]
## Implementation landing spot (prep, 2026-08-15)

Binding condition 1 from the #4378 vote says the predicate goes *inside the existing `CompositeRouter` stage chain, not a new module*. Locating exactly where that is, so the implementation doesn't have to rediscover it.

**There is already a composable stage architecture** at `cli-adapters/routing/stages/` implementing `IRouterStage`, with explicit priorities:

| Priority | Stage |
|---|---|
| 10 | `ConfidenceCascadeStage` |
| **20** | **`BudgetFilterStage`** ← closest analog |
| 35 | `CapabilityMatchStage` |
| 40 | `ZeroRouterStage` |
| 50 | `PreferenceStage` |
| 55 | `ResourceStrategyStage` |
| 60 | `TopsisRouterStage` |
| 70 | `LinUCBStage` |
| 75 | `QualityConstraintStage` |

`BudgetFilterStage` (`routing/stages/budget-stage.ts`, 262 lines) is the template: it is *already* an exclusion predicate over candidates, and it imports the shared primitives this issue needs —

```ts
import { addTrace, filterCandidate, getRemainingCandidates } from '../router-stage.js';
```

`filterCandidate` is the canonical exclusion mechanism. A `CapacityFilterStage` should use it rather than inventing exclusion logic, and should sit **adjacent to budget at priority ~25** — both are hard pre-scoring filters, and capacity is cheaper to evaluate than capability matching, so excluding an exhausted arm before the scoring stages avoids wasted work.

**This satisfies binding condition 1 rather than violating it.** Adding a stage file under `routing/stages/` is not "a new module" in the sense the vote prohibited — it is the chain's own documented extension point (ADR-0005), and the scope steward's condition explicitly allowed *"rung 3: extend the canonical substrate primitive"*. What was prohibited was reviving or grafting on a parallel component.

**Open question for implementation:** `BudgetStageConfig` has an `enforceHardLimits: boolean` (filter out vs. warn only). Capacity exclusion should probably mirror that — a soft mode that annotates the trace without filtering is what makes this safely rollout-able, and it matches how #4351's other criteria were staged. Worth deciding explicitly rather than defaulting to hard-filter.

**Comment by williamzujkowski** [comment]
## Design constraint found before implementing: `CapacityStatus.observed` (#4374)

Two findings from mapping the contract, both of which change the implementation.

### 1. This is NOT duplicative — the routing chain has no capacity exclusion today

Worth confirming explicitly, given #4378 was just deleted for being a parallel mechanism. There **is** an existing exclusion path, but it is elsewhere: the shared circuit-breaker registry gates **voter-panel availability** (#4330, `cli-circuit-breaker.ts:92`), and `ResilientAdapter` consumes it. `CompositeRouter` does not consult it. Greps for breaker/circuit state in `composite-router.ts` and `composite-router-stages.ts` return nothing but an unrelated comment.

So: breaker = failure-driven exclusion for voting; this issue = quota-driven exclusion for routing. Different signals, different surfaces, no overlap.

### 2. The blocking constraint: an unobserved capacity reading is fabricated, not measured

`CapacityStatus` (`cli-adapters/types-core.ts:189-214`) carries an `observed` flag added by #4374, and its docstring is explicit:

> When false, every other field is a *default*, not a measurement: a tracker that has never recorded a request reports the full token limit remaining and 0% utilization, which is indistinguishable from a genuinely idle adapter. **Consumers must not present an unobserved reading as health.**
>
> Note the narrower guarantee even when true: the tracker sees only THIS process's spend. It has no visibility into a provider-side weekly quota consumed elsewhere, so `remainingTokens` is a local upper bound on what is left, never an authoritative one.

**This directly contradicts the naive port of the deleted `getCapacityScore` formula I recorded earlier in this issue.** That formula computes `remainingTokens / estimatedTokens` with no notion of whether the reading is real. Against an unobserved adapter it would compute a ratio from a default and score it `10` — maximum health from zero data. That is exactly the failure mode #4435/#4439 fixed elsewhere in this tree, where an absent measurement was coerced into a present value and became indistinguishable downstream from a real one.

**Binding rules for the implementation:**

1. **Exclude only on `observed === true`.** An unobserved adapter is never excluded — fail *open* on absent data, because exclusion is a destructive decision and we have no evidence.
2. **Never treat unobserved as healthy either.** Do not let a defaulted `remainingTokens` contribute a positive score or clear a check. Absence is neither exclusion nor endorsement.
3. **`remainingTokens` is a local upper bound.** Even when observed, it misses provider-side quota spent by other processes — so a non-zero reading is not proof of available quota. This argues for exclusion keyed on the explicit `exhausted` flag plus `remainingTokens <= 0`, rather than on a ratio threshold that implies more precision than the data supports.
4. The trace/diagnostic must distinguish *not excluded because healthy* from *not excluded because unmeasured* — otherwise the same #4436-style blindness reappears in the routing trace.

### 3. Correction to my earlier design note in this thread

I wrote that the stage should sit at "priority ~25" alongside `BudgetFilterStage`. **The `priority` field is decorative for this router.** `IRouterStage.priority` is only honoured by `RoutingPipeline` (`routing/routing-pipeline.ts`), which `CompositeRouter` does not use. `CompositeRouter` hand-wires each stage in `composite-router-stages.ts`, where **insertion order in the function body IS the pipeline order**. Placement is therefore a code-position decision, not a number.

Registration requires four edits: `composite-router-types.ts` (config flag + default), `composite-router.ts` (private field + construction), `composite-router-stages.ts` (`StageDependencies` member + run function + call site), `routing/stages/index.ts` (export).

Also note `RoutingContext` carries no adapter or capacity reference — only `availableClis: readonly CliName[]` — so adapters must be injected into the stage constructor, mirroring `BudgetRouter(adapters, ...)`.

**Comment by williamzujkowski** [comment]
## Default-posture vote: **7/7 for Option A — enforce by default**

Live 7-voter panel, `supermajority` strategy, `errorPolicy: absolute_quorum`, no simulated votes, record persisted.

Unlike the #4378 breaking-change vote (which the tool reported as 7/0 while the real split was 6–1 on the option — see #4452), this one **is** genuinely unanimous on the option itself: all seven voters chose A. Option B got zero, C got zero.

### The argument that carried it: error asymmetry, not confidence

Every voter independently arrived at the same structural point, which is stronger than the one I put in the proposal:

> The local tracker sees only *this* process's spend, so `remainingTokens` is an **upper bound** on what is actually left. Therefore if the tracker *observed* exhaustion, the provider-side quota is **at least** as exhausted. An observed-exhaustion exclusion is close to tautologically correct.

The entire error budget lives on the false-**negative** side — missing exhaustion the local tracker cannot see. And a false negative is precisely today's behaviour, the open bug #4351. Enforcing cannot make that dimension worse. That collapses the case for a warn stage: staging exists to gather evidence about false positives, and the `observed` gate suppresses the mechanism that produces them.

### Why B was rejected outright

The proposal asked who consumes warn-mode telemetry. The panel's answer was that nobody does, and therefore **B degenerates into C with extra steps**: a warn signal nobody reads produces no evidence, so there is no trigger to flip on. Several voters cited this repo's own record — #2795 (context-injection) and #4262 (repo-map) are still gated — and the capability-bias rule's requirement that a capability ship *with the instrumentation to judge it*. A warn default was called "process theater" by one voter and "an uninstrumented promise" by another.

### The dissent that isn't a dissent — and the honest limitation

The contrarian voted A but attached the sharpest caveat, which I am recording rather than burying because it qualifies the fix:

> **`observed === true` protects against ABSENT evidence, not WRONG evidence.** A stale or misconfigured local limit — plan changed, weekly-window boundary bug, limit set below actual quota — yields a confident false positive the gate waves straight through.

And on scope:

> In the #4351 live incident, if the weekly quota was burned **outside** this process, the local tracker would never have observed it — meaning A only fixes the subset of #4351 the tracker can see.

Both are true and neither is designed around. **This closes criterion 3 for locally-observable exhaustion only.** Provider-side quota consumed by other processes remains invisible, so #4351's original scenario is only partially addressed by this stage. Worth stating plainly rather than claiming the criterion is fully discharged.

### Binding condition, implemented

Two voters (devex, security) required that the all-excluded fail-closed path be explicit and diagnosed rather than a silent empty pool:

> that must be an explicit, diagnosed, tested outcome, not a silent empty-pool error
>
> an excluded candidate that says why beats a hung task that doesn't

My first implementation failed this — it raised a bare `capacity_exhausted` code. Fixed: the error now names every excluded arm with its reason, and a test asserts each name appears in the message. Leaving it bare would have reproduced the exact #4351 complaint that nexus "did not explain it in the terminal result".

**Comment by williamzujkowski** [comment]
## Implementation note: a resilience bug the full suite caught (2026-08-15)

Recording this because the failure mode is subtle and would have shipped as a routing outage.

**Symptom.** After wiring the stage, 6 tests in `cli-adapters/pipeline-e2e.test.ts` failed with `routeResult.ok === false` — the entire routing call was failing, not just capacity assessment.

**Cause.** That suite's mock adapter (`pipeline-e2e.test.ts:29`) does not implement `getCapacity`. My probe was:

```ts
candidates.map((cli) => {
  const adapter = this.adapters.get(cli);
  return adapter === undefined
    ? Promise.reject(new Error('no adapter registered'))
    : adapter.getCapacity();   // <-- TypeError, thrown SYNCHRONOUSLY
})
```

Calling a missing method throws a `TypeError` **synchronously inside the `.map()` callback** — before `Promise.allSettled` ever receives an array. So it escaped the settle entirely and rejected `route()`.

**Why this mattered beyond a test fixture.** The stage was designed to fail open on absent evidence, and it did — for *rejected* probes. It did not for *synchronous throws*. The practical consequence: an adapter that is structurally partial (no `getCapacity`) would take down routing for **every** candidate, not just itself. A capacity filter causing a total routing failure is the precise inverse of its purpose, and it is the same never-throws-contract class as #4303/#4308.

**Fix.** Make the callback `async`, which converts a synchronous throw into a rejection so it lands in the `unmeasured` branch like any other bad probe:

```ts
candidates.map(async (cli) => {
  const adapter = this.adapters.get(cli);
  if (adapter === undefined) throw new Error('no adapter registered');
  return adapter.getCapacity();
})
```

**Verified by mutation, not just by going green.** Reverting the fix reproduces the failure in both places — the e2e suite *and* the new dedicated regression test (`survives an adapter that does not implement getCapacity at all`) fail together; restoring it turns both green. So the regression test is not vacuous: it fails for the reason it claims to.

Worth noting the full suite is what caught this. The 14 stage-level tests were green throughout, because every one of them supplies a well-formed adapter stub. A targeted test file cannot find a defect that only appears against a differently-shaped mock.

**Comment by williamzujkowski** [comment]
## Correction: the 7/7 enforce-by-default vote rested on a false premise I supplied. Default flipped to signal-only.

Adversarial review of the actual diff found that `CapacityStatus.exhausted` does not mean what I told the panel it meant. The vote's decisive reasoning does not survive the correction, so I am not shipping its conclusion.

### What I told the panel

> The local tracker sees only THIS process's spend, so `remainingTokens` is a local upper bound, never authoritative. Consequence: the stage can MISS a genuinely exhausted adapter (false negative), but a false POSITIVE requires the local tracker to have actually observed exhaustion.

Every voter built on that. The architect: *"the known error mode is the false NEGATIVE… so enforcing cannot regress availability relative to the status quo."* The scope steward: *"if the tracker OBSERVED exhaustion, the provider-side quota is at least as exhausted. An observed-exhaustion exclusion is close to tautologically correct."*

### What it actually is

`cli-adapters/capacity-tracker.ts`:

```ts
export const DEFAULT_TOKEN_LIMITS   = { claude: 100_000, ... };  // "conservative estimates"
export const DEFAULT_REQUEST_LIMITS = { claude: 50, ... };
export const RATE_LIMIT_WINDOW_MS   = 60_000;
// :184
const exhausted = remainingTokens === 0 || remainingRequests === 0;
```

`exhausted === true` means **this process made 50 claude calls, or spent 100k claude tokens, in a rolling 60 seconds** — against a hardcoded guess at one API tier — and it self-clears within the minute (`resetTime = windowStart + windowMs`). `recordUsage` (`:151`) pushes a request timestamp unconditionally, so request-count exhaustion trips even with no token accounting at all. It is live from the first call: `base-adapter.ts:213` feeds it after every execution and `hasObserved` flips true immediately.

### Why the vote's logic fails

"Local spend is a lower bound on provider-side spend" is true of *quota*. It is not true of a *per-minute rate window*. Burning 50 requests in 60 seconds implies nothing whatsoever about weekly plan quota — the two are different quantities, not the same quantity measured incompletely. So:

- **The premise that false positives are near-impossible is wrong.** A 7-voter consensus panel or a subagent fan-out is exactly the traffic shape that trips a 50-req/60s counter while plenty of quota remains.
- **The claimed fix does not fix the reported bug.** #4351 was *weekly quota* exhaustion. Quota burned gradually, or burned by another process, never trips a rolling-60s counter. The stage as voted could not have detected the incident it was built for.
- **Enforcing would add a failure mode.** Once all four slots trip, `runCapacityStage` returns an error and routing hard-fails — with no retry or backoff — for a condition that clears itself in under a minute. A self-inflicted outage.

### What I changed

**`DEFAULT_CONFIG.enforceHardLimits` is now `false`.** The stage classifies, traces, and emits `capacity_exhausted` and `capacity:unmeasured-N` signals, but does not remove candidates. `enforceHardLimits: true` remains available for a caller with a trustworthy signal. A test at the *wiring* boundary asserts the shipped default is signal-only, so re-enabling enforcement must break a test rather than pass silently.

Filed **#4456** for the actual gap: there is no durable quota signal anywhere in the tree. It proposes distinguishing `rateLimited` (short, self-clearing) from `quotaExhausted` (durable, provider-asserted, from rate-limit headers or a classified quota error per #4382), and enforcing only on the latter.

### On the option the panel rejected

The panel dismissed warn-only 7/0, largely on my framing that nothing consumes warn telemetry so it degenerates into off-by-default. That objection was reasonable given what I told them, and it is now answered on its own terms: the named consumer of the signal is **#4456's decision about whether the signal is trustworthy enough to enforce on** — which is a real question with a real owner, not an indefinite park.

I am not re-running the vote. The panel decided a question whose factual basis I got wrong; re-asking it with corrected facts would be reasonable, but the corrected facts make signal-only the only safe option, and there is no fork left to put to a panel. **#4373 therefore does not close #4351 criterion 3** — I will leave that criterion open on #4351 rather than mark it done.

### Also fixed from the same review

- **Unguarded boundary throw** — `runCapacityStage` awaited `route()` without a try/catch, so an escaped throw would reject the whole routing call. That is the same failure class as the synchronous-throw bug I had already fixed *inside* `assessAll`; guarding one level down while leaving the boundary open only moved it.
- **No probe timeout** — `getCapacity()` is an unbounded promise on a public interface and `maxDecisionTimeMs` is declared but enforced nowhere, so one hanging adapter stalled all routing. Added `probeTimeoutMs` (2s); a timed-out probe is `unmeasured`, never `exhausted`.
- **A tautological test** — `expect(signals).not.toContain('capacity:unmeasured-0')` sat inside a case where the count was 1, so no implementation could fail it. Replaced with a real complement asserting no unmeasured signal when every candidate was measured.
- **JSDoc contradicting code** — a comment claimed the unmeasured signal was emitted at zero to distinguish "all healthy" from "all unknown"; it never was. Corrected to describe actual behaviour.
